In [1]:
import torch

x = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [2]:
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [3]:
import numpy as np

# グラフ: 1 --- 2 --- 3 --- 4 --- 5
# ノード数
n = 5

# 隣接行列 (Adjacency Matrix)
A = np.array([
    [0, 1, 0, 0, 0],  # ノード1: 2と接続
    [1, 0, 1, 0, 0],  # ノード2: 1, 3と接続
    [0, 1, 0, 1, 0],  # ノード3: 2, 4と接続
    [0, 0, 1, 0, 1],  # ノード4: 3, 5と接続
    [0, 0, 0, 1, 0]   # ノード5: 4と接続
])

print("隣接行列 (Adjacency Matrix):")
print(A)
print()

# 次数行列 (Degree Matrix)
D = np.diag(A.sum(axis=1))
print("次数行列 (Degree Matrix):")
print(D)
print()

# ラプラシアン行列 (Laplacian Matrix): L = D - A
L = D - A
print("ラプラシアン行列 (Laplacian Matrix):")
print(L)
print()

隣接行列 (Adjacency Matrix):
[[0 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]

次数行列 (Degree Matrix):
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]

ラプラシアン行列 (Laplacian Matrix):
[[ 1 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  1]]



In [5]:
# ラプラシアン行列の固有値と固有ベクトルを計算
eigenvalues, eigenvectors = np.linalg.eig(L)

# 固有値を昇順にソート
sorted_indices = np.argsort(eigenvalues)
eigenvalues_sorted = eigenvalues[sorted_indices]
eigenvectors_sorted = eigenvectors[:, sorted_indices]

print("固有値 (昇順):")
for i, val in enumerate(eigenvalues_sorted):
    print(f"λ{i} = {val:.2f}")
print()

固有値 (昇順):
λ0 = 0.00
λ1 = 0.38
λ2 = 1.38
λ3 = 2.62
λ4 = 3.62



In [8]:
print("固有ベクトル (各列が対応する固有ベクトル):")
print(eigenvectors_sorted)
print()

# 各固有値に対応する固有ベクトルを個別に表示
for i in range(n):
    print(f"固有値 λ{i} = {eigenvalues_sorted[i]:.2f} に対応する固有ベクトル:")
    print(eigenvectors_sorted[:, i])
    print()

固有ベクトル (各列が対応する固有ベクトル):
[[ 4.47213595e-01 -6.01500955e-01  5.11667274e-01  3.71748034e-01
   1.95439508e-01]
 [ 4.47213595e-01 -3.71748034e-01 -1.95439508e-01 -6.01500955e-01
  -5.11667274e-01]
 [ 4.47213595e-01 -2.78155845e-16 -6.32455532e-01  2.95779963e-16
   6.32455532e-01]
 [ 4.47213595e-01  3.71748034e-01 -1.95439508e-01  6.01500955e-01
  -5.11667274e-01]
 [ 4.47213595e-01  6.01500955e-01  5.11667274e-01 -3.71748034e-01
   1.95439508e-01]]

固有値 λ0 = 0.00 に対応する固有ベクトル:
[0.4472136 0.4472136 0.4472136 0.4472136 0.4472136]

固有値 λ1 = 0.38 に対応する固有ベクトル:
[-6.01500955e-01 -3.71748034e-01 -2.78155845e-16  3.71748034e-01
  6.01500955e-01]

固有値 λ2 = 1.38 に対応する固有ベクトル:
[ 0.51166727 -0.19543951 -0.63245553 -0.19543951  0.51166727]

固有値 λ3 = 2.62 に対応する固有ベクトル:
[ 3.71748034e-01 -6.01500955e-01  2.95779963e-16  6.01500955e-01
 -3.71748034e-01]

固有値 λ4 = 3.62 に対応する固有ベクトル:
[ 0.19543951 -0.51166727  0.63245553 -0.51166727  0.19543951]

